version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
shallow_clone: true
clone_depth: 10
assembly_info:
  patch: true
  file: SteamAccCreator\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test: off
artifacts:
- path: SteamAccCreator\bin\$(configuration)
  name: Release-windows-$(appveyor_build_version)
